// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: daemon.proto

package daemon

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FreeMemoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FreeMemoryRequest) Reset() {
	*x = FreeMemoryRequest{}
	mi := &file_daemon_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FreeMemoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FreeMemoryRequest) ProtoMessage() {}

func (x *FreeMemoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FreeMemoryRequest.ProtoReflect.Descriptor instead.
func (*FreeMemoryRequest) Descriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{0}
}

type FreeMemoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	MemoryBytes   uint64                 `protobuf:"varint,2,opt,name=memory_bytes,json=memoryBytes,proto3" json:"memory_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FreeMemoryResponse) Reset() {
	*x = FreeMemoryResponse{}
	mi := &file_daemon_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FreeMemoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FreeMemoryResponse) ProtoMessage() {}

func (x *FreeMemoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FreeMemoryResponse.ProtoReflect.Descriptor instead.
func (*FreeMemoryResponse) Descriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{1}
}

func (x *FreeMemoryResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *FreeMemoryResponse) GetMemoryBytes() uint64 {
	if x != nil {
		return x.MemoryBytes
	}
	return 0
}

type GetStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusRequest) Reset() {
	*x = GetStatusRequest{}
	mi := &file_daemon_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusRequest) ProtoMessage() {}

func (x *GetStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusRequest.ProtoReflect.Descriptor instead.
func (*GetStatusRequest) Descriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{2}
}

type GetStatusResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Connected      bool                   `protobuf:"varint,1,opt,name=connected,proto3" json:"connected,omitempty"`
	SteamId        string                 `protobuf:"bytes,2,opt,name=steam_id,json=steamId,proto3" json:"steam_id,omitempty"`
	CurrentAppid   uint32                 `protobuf:"varint,3,opt,name=current_appid,json=currentAppid,proto3" json:"current_appid,omitempty"`
	Uptime         string                 `protobuf:"bytes,4,opt,name=uptime,proto3" json:"uptime,omitempty"`
	MemoryBytes    uint64                 `protobuf:"varint,5,opt,name=memory_bytes,json=memoryBytes,proto3" json:"memory_bytes,omitempty"`
	CurrentAppName string                 `protobuf:"bytes,6,opt,name=current_app_name,json=currentAppName,proto3" json:"current_app_name,omitempty"`
	PersonaName    string                 `protobuf:"bytes,7,opt,name=persona_name,json=personaName,proto3" json:"persona_name,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetStatusResponse) Reset() {
	*x = GetStatusResponse{}
	mi := &file_daemon_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusResponse) ProtoMessage() {}

func (x *GetStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusResponse.ProtoReflect.Descriptor instead.
func (*GetStatusResponse) Descriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{3}
}

func (x *GetStatusResponse) GetConnected() bool {
	if x != nil {
		return x.Connected
	}
	return false
}

func (x *GetStatusResponse) GetSteamId() string {
	if x != nil {
		return x.SteamId
	}
	return ""
}

func (x *GetStatusResponse) GetCurrentAppid() uint32 {
	if x != nil {
		return x.CurrentAppid
	}
	return 0
}

func (x *GetStatusResponse) GetUptime() string {
	if x != nil {
		return x.Uptime
	}
	return ""
}

func (x *GetStatusResponse) GetMemoryBytes() uint64 {
	if x != nil {
		return x.MemoryBytes
	}
	return 0
}

func (x *GetStatusResponse) GetCurrentAppName() string {
	if x != nil {
		return x.CurrentAppName
	}
	return ""
}

func (x *GetStatusResponse) GetPersonaName() string {
	if x != nil {
		return x.PersonaName
	}
	return ""
}

type StopDaemonRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopDaemonRequest) Reset() {
	*x = StopDaemonRequest{}
	mi := &file_daemon_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopDaemonRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopDaemonRequest) ProtoMessage() {}

func (x *StopDaemonRequest) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopDaemonRequest.ProtoReflect.Descriptor instead.
func (*StopDaemonRequest) Descriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{4}
}

type StopDaemonResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopDaemonResponse) Reset() {
	*x = StopDaemonResponse{}
	mi := &file_daemon_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopDaemonResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopDaemonResponse) ProtoMessage() {}

func (x *StopDaemonResponse) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopDaemonResponse.ProtoReflect.Descriptor instead.
func (*StopDaemonResponse) Descriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{5}
}

func (x *StopDaemonResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type PlayGameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Appid         uint32                 `protobuf:"varint,1,opt,name=appid,proto3" json:"appid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayGameRequest) Reset() {
	*x = PlayGameRequest{}
	mi := &file_daemon_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayGameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayGameRequest) ProtoMessage() {}

func (x *PlayGameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayGameRequest.ProtoReflect.Descriptor instead.
func (*PlayGameRequest) Descriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{6}
}

func (x *PlayGameRequest) GetAppid() uint32 {
	if x != nil {
		return x.Appid
	}
	return 0
}

type PlayGameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayGameResponse) Reset() {
	*x = PlayGameResponse{}
	mi := &file_daemon_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayGameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayGameResponse) ProtoMessage() {}

func (x *PlayGameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayGameResponse.ProtoReflect.Descriptor instead.
func (*PlayGameResponse) Descriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{7}
}

func (x *PlayGameResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ExitGameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExitGameRequest) Reset() {
	*x = ExitGameRequest{}
	mi := &file_daemon_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExitGameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExitGameRequest) ProtoMessage() {}

func (x *ExitGameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExitGameRequest.ProtoReflect.Descriptor instead.
func (*ExitGameRequest) Descriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{8}
}

type ExitGameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExitGameResponse) Reset() {
	*x = ExitGameResponse{}
	mi := &file_daemon_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExitGameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExitGameResponse) ProtoMessage() {}

func (x *ExitGameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExitGameResponse.ProtoReflect.Descriptor instead.
func (*ExitGameResponse) Descriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{9}
}

func (x *ExitGameResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Item struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AssetId       uint64                 `protobuf:"varint,1,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	DefIndex      uint32                 `protobuf:"varint,2,opt,name=def_index,json=defIndex,proto3" json:"def_index,omitempty"`
	Quality       uint32                 `protobuf:"varint,3,opt,name=quality,proto3" json:"quality,omitempty"`
	Quantity      uint32                 `protobuf:"varint,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	IsTradable    bool                   `protobuf:"varint,5,opt,name=is_tradable,json=isTradable,proto3" json:"is_tradable,omitempty"`
	IsCraftable   bool                   `protobuf:"varint,6,opt,name=is_craftable,json=isCraftable,proto3" json:"is_craftable,omitempty"`
	Attributes    map[string]string      `protobuf:"bytes,7,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	OriginalId    uint64                 `protobuf:"varint,8,opt,name=original_id,json=originalId,proto3" json:"original_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Item) Reset() {
	*x = Item{}
	mi := &file_daemon_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item.ProtoReflect.Descriptor instead.
func (*Item) Descriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{10}
}

func (x *Item) GetAssetId() uint64 {
	if x != nil {
		return x.AssetId
	}
	return 0
}

func (x *Item) GetDefIndex() uint32 {
	if x != nil {
		return x.DefIndex
	}
	return 0
}

func (x *Item) GetQuality() uint32 {
	if x != nil {
		return x.Quality
	}
	return 0
}

func (x *Item) GetQuantity() uint32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *Item) GetIsTradable() bool {
	if x != nil {
		return x.IsTradable
	}
	return false
}

func (x *Item) GetIsCraftable() bool {
	if x != nil {
		return x.IsCraftable
	}
	return false
}

func (x *Item) GetAttributes() map[string]string {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *Item) GetOriginalId() uint64 {
	if x != nil {
		return x.OriginalId
	}
	return 0
}

type ExecActionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Appid         uint32                 `protobuf:"varint,1,opt,name=appid,proto3" json:"appid,omitempty"`
	Action        string                 `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	Params        map[string]string      `protobuf:"bytes,3,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecActionRequest) Reset() {
	*x = ExecActionRequest{}
	mi := &file_daemon_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecActionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecActionRequest) ProtoMessage() {}

func (x *ExecActionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecActionRequest.ProtoReflect.Descriptor instead.
func (*ExecActionRequest) Descriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{11}
}

func (x *ExecActionRequest) GetAppid() uint32 {
	if x != nil {
		return x.Appid
	}
	return 0
}

func (x *ExecActionRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *ExecActionRequest) GetParams() map[string]string {
	if x != nil {
		return x.Params
	}
	return nil
}

type ExecActionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Items         []*Item                `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	Details       string                 `protobuf:"bytes,3,opt,name=details,proto3" json:"details,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecActionResponse) Reset() {
	*x = ExecActionResponse{}
	mi := &file_daemon_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecActionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecActionResponse) ProtoMessage() {}

func (x *ExecActionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecActionResponse.ProtoReflect.Descriptor instead.
func (*ExecActionResponse) Descriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{12}
}

func (x *ExecActionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ExecActionResponse) GetItems() []*Item {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ExecActionResponse) GetDetails() string {
	if x != nil {
		return x.Details
	}
	return ""
}

type StreamEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamEventsRequest) Reset() {
	*x = StreamEventsRequest{}
	mi := &file_daemon_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamEventsRequest) ProtoMessage() {}

func (x *StreamEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamEventsRequest.ProtoReflect.Descriptor instead.
func (*StreamEventsRequest) Descriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{13}
}

type StreamEventsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	EventType     string                 `protobuf:"bytes,2,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	PayloadJson   string                 `protobuf:"bytes,3,opt,name=payload_json,json=payloadJson,proto3" json:"payload_json,omitempty"`
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamEventsResponse) Reset() {
	*x = StreamEventsResponse{}
	mi := &file_daemon_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamEventsResponse) ProtoMessage() {}

func (x *StreamEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamEventsResponse.ProtoReflect.Descriptor instead.
func (*StreamEventsResponse) Descriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{14}
}

func (x *StreamEventsResponse) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *StreamEventsResponse) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *StreamEventsResponse) GetPayloadJson() string {
	if x != nil {
		return x.PayloadJson
	}
	return ""
}

func (x *StreamEventsResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type ManualPriceEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BuyKeys       uint32                 `protobuf:"varint,1,opt,name=buy_keys,json=buyKeys,proto3" json:"buy_keys,omitempty"`
	BuyMetal      float64                `protobuf:"fixed64,2,opt,name=buy_metal,json=buyMetal,proto3" json:"buy_metal,omitempty"`
	SellKeys      uint32                 `protobuf:"varint,3,opt,name=sell_keys,json=sellKeys,proto3" json:"sell_keys,omitempty"`
	SellMetal     float64                `protobuf:"fixed64,4,opt,name=sell_metal,json=sellMetal,proto3" json:"sell_metal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ManualPriceEntry) Reset() {
	*x = ManualPriceEntry{}
	mi := &file_daemon_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManualPriceEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManualPriceEntry) ProtoMessage() {}

func (x *ManualPriceEntry) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManualPriceEntry.ProtoReflect.Descriptor instead.
func (*ManualPriceEntry) Descriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{15}
}

func (x *ManualPriceEntry) GetBuyKeys() uint32 {
	if x != nil {
		return x.BuyKeys
	}
	return 0
}

func (x *ManualPriceEntry) GetBuyMetal() float64 {
	if x != nil {
		return x.BuyMetal
	}
	return 0
}

func (x *ManualPriceEntry) GetSellKeys() uint32 {
	if x != nil {
		return x.SellKeys
	}
	return 0
}

func (x *ManualPriceEntry) GetSellMetal() float64 {
	if x != nil {
		return x.SellMetal
	}
	return 0
}

type UpdateManualPricesRequest struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Prices        map[string]*ManualPriceEntry `protobuf:"bytes,1,rep,name=prices,proto3" json:"prices,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateManualPricesRequest) Reset() {
	*x = UpdateManualPricesRequest{}
	mi := &file_daemon_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateManualPricesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateManualPricesRequest) ProtoMessage() {}

func (x *UpdateManualPricesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateManualPricesRequest.ProtoReflect.Descriptor instead.
func (*UpdateManualPricesRequest) Descriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{16}
}

func (x *UpdateManualPricesRequest) GetPrices() map[string]*ManualPriceEntry {
	if x != nil {
		return x.Prices
	}
	return nil
}

type UpdateManualPricesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateManualPricesResponse) Reset() {
	*x = UpdateManualPricesResponse{}
	mi := &file_daemon_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateManualPricesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateManualPricesResponse) ProtoMessage() {}

func (x *UpdateManualPricesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateManualPricesResponse.ProtoReflect.Descriptor instead.
func (*UpdateManualPricesResponse) Descriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{17}
}

func (x *UpdateManualPricesResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UpdateManualPricesResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GuardCodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GuardCodeRequest) Reset() {
	*x = GuardCodeRequest{}
	mi := &file_daemon_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GuardCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuardCodeRequest) ProtoMessage() {}

func (x *GuardCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuardCodeRequest.ProtoReflect.Descriptor instead.
func (*GuardCodeRequest) Descriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{18}
}

type GuardCodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GuardCodeResponse) Reset() {
	*x = GuardCodeResponse{}
	mi := &file_daemon_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GuardCodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuardCodeResponse) ProtoMessage() {}

func (x *GuardCodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuardCodeResponse.ProtoReflect.Descriptor instead.
func (*GuardCodeResponse) Descriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{19}
}

func (x *GuardCodeResponse) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type GuardConfirmation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Nonce         uint64                 `protobuf:"varint,2,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	TypeName      string                 `protobuf:"bytes,4,opt,name=type_name,json=typeName,proto3" json:"type_name,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GuardConfirmation) Reset() {
	*x = GuardConfirmation{}
	mi := &file_daemon_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GuardConfirmation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuardConfirmation) ProtoMessage() {}

func (x *GuardConfirmation) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuardConfirmation.ProtoReflect.Descriptor instead.
func (*GuardConfirmation) Descriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{20}
}

func (x *GuardConfirmation) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GuardConfirmation) GetNonce() uint64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

func (x *GuardConfirmation) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *GuardConfirmation) GetTypeName() string {
	if x != nil {
		return x.TypeName
	}
	return ""
}

func (x *GuardConfirmation) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type GuardListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GuardListRequest) Reset() {
	*x = GuardListRequest{}
	mi := &file_daemon_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GuardListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuardListRequest) ProtoMessage() {}

func (x *GuardListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuardListRequest.ProtoReflect.Descriptor instead.
func (*GuardListRequest) Descriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{21}
}

type GuardListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Confirmations []*GuardConfirmation   `protobuf:"bytes,1,rep,name=confirmations,proto3" json:"confirmations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GuardListResponse) Reset() {
	*x = GuardListResponse{}
	mi := &file_daemon_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GuardListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuardListResponse) ProtoMessage() {}

func (x *GuardListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuardListResponse.ProtoReflect.Descriptor instead.
func (*GuardListResponse) Descriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{22}
}

func (x *GuardListResponse) GetConfirmations() []*GuardConfirmation {
	if x != nil {
		return x.Confirmations
	}
	return nil
}

type GuardRespondRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConfirmationId uint64                 `protobuf:"varint,1,opt,name=confirmation_id,json=confirmationId,proto3" json:"confirmation_id,omitempty"`
	Accept         bool                   `protobuf:"varint,2,opt,name=accept,proto3" json:"accept,omitempty"`
	All            bool                   `protobuf:"varint,3,opt,name=all,proto3" json:"all,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GuardRespondRequest) Reset() {
	*x = GuardRespondRequest{}
	mi := &file_daemon_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GuardRespondRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuardRespondRequest) ProtoMessage() {}

func (x *GuardRespondRequest) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuardRespondRequest.ProtoReflect.Descriptor instead.
func (*GuardRespondRequest) Descriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{23}
}

func (x *GuardRespondRequest) GetConfirmationId() uint64 {
	if x != nil {
		return x.ConfirmationId
	}
	return 0
}

func (x *GuardRespondRequest) GetAccept() bool {
	if x != nil {
		return x.Accept
	}
	return false
}

func (x *GuardRespondRequest) GetAll() bool {
	if x != nil {
		return x.All
	}
	return false
}

type GuardRespondResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GuardRespondResponse) Reset() {
	*x = GuardRespondResponse{}
	mi := &file_daemon_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GuardRespondResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuardRespondResponse) ProtoMessage() {}

func (x *GuardRespondResponse) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuardRespondResponse.ProtoReflect.Descriptor instead.
func (*GuardRespondResponse) Descriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{24}
}

func (x *GuardRespondResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GuardRespondResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GuardStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GuardStatusRequest) Reset() {
	*x = GuardStatusRequest{}
	mi := &file_daemon_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GuardStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuardStatusRequest) ProtoMessage() {}

func (x *GuardStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuardStatusRequest.ProtoReflect.Descriptor instead.
func (*GuardStatusRequest) Descriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{25}
}

type GuardStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Configured    bool                   `protobuf:"varint,1,opt,name=configured,proto3" json:"configured,omitempty"`
	DeviceId      string                 `protobuf:"bytes,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	SteamId       string                 `protobuf:"bytes,3,opt,name=steam_id,json=steamId,proto3" json:"steam_id,omitempty"`
	State         uint32                 `protobuf:"varint,4,opt,name=state,proto3" json:"state,omitempty"`
	SharedSecret  string                 `protobuf:"bytes,5,opt,name=shared_secret,json=sharedSecret,proto3" json:"shared_secret,omitempty"`
	Uri           string                 `protobuf:"bytes,6,opt,name=uri,proto3" json:"uri,omitempty"`
	AccountName   string                 `protobuf:"bytes,7,opt,name=account_name,json=accountName,proto3" json:"account_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GuardStatusResponse) Reset() {
	*x = GuardStatusResponse{}
	mi := &file_daemon_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GuardStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuardStatusResponse) ProtoMessage() {}

func (x *GuardStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuardStatusResponse.ProtoReflect.Descriptor instead.
func (*GuardStatusResponse) Descriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{26}
}

func (x *GuardStatusResponse) GetConfigured() bool {
	if x != nil {
		return x.Configured
	}
	return false
}

func (x *GuardStatusResponse) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *GuardStatusResponse) GetSteamId() string {
	if x != nil {
		return x.SteamId
	}
	return ""
}

func (x *GuardStatusResponse) GetState() uint32 {
	if x != nil {
		return x.State
	}
	return 0
}

func (x *GuardStatusResponse) GetSharedSecret() string {
	if x != nil {
		return x.SharedSecret
	}
	return ""
}

func (x *GuardStatusResponse) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *GuardStatusResponse) GetAccountName() string {
	if x != nil {
		return x.AccountName
	}
	return ""
}

type GuardImportRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SharedSecret   string                 `protobuf:"bytes,1,opt,name=shared_secret,json=sharedSecret,proto3" json:"shared_secret,omitempty"`
	IdentitySecret string                 `protobuf:"bytes,2,opt,name=identity_secret,json=identitySecret,proto3" json:"identity_secret,omitempty"`
	DeviceId       string                 `protobuf:"bytes,3,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	AccountName    string                 `protobuf:"bytes,4,opt,name=account_name,json=accountName,proto3" json:"account_name,omitempty"`
	RefreshToken   string                 `protobuf:"bytes,5,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GuardImportRequest) Reset() {
	*x = GuardImportRequest{}
	mi := &file_daemon_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GuardImportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuardImportRequest) ProtoMessage() {}

func (x *GuardImportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuardImportRequest.ProtoReflect.Descriptor instead.
func (*GuardImportRequest) Descriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{27}
}

func (x *GuardImportRequest) GetSharedSecret() string {
	if x != nil {
		return x.SharedSecret
	}
	return ""
}

func (x *GuardImportRequest) GetIdentitySecret() string {
	if x != nil {
		return x.IdentitySecret
	}
	return ""
}

func (x *GuardImportRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *GuardImportRequest) GetAccountName() string {
	if x != nil {
		return x.AccountName
	}
	return ""
}

func (x *GuardImportRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type GuardImportResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GuardImportResponse) Reset() {
	*x = GuardImportResponse{}
	mi := &file_daemon_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GuardImportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuardImportResponse) ProtoMessage() {}

func (x *GuardImportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuardImportResponse.ProtoReflect.Descriptor instead.
func (*GuardImportResponse) Descriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{28}
}

func (x *GuardImportResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GuardImportResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_daemon_proto protoreflect.FileDescriptor

const file_daemon_proto_rawDesc = "" +
	"\n" +
	"\fdaemon.proto\x12\x06daemon\"\x13\n" +
	"\x11FreeMemoryRequest\"Q\n" +
	"\x12FreeMemoryResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12!\n" +
	"\fmemory_bytes\x18\x02 \x01(\x04R\vmemoryBytes\"\x12\n" +
	"\x10GetStatusRequest\"\xf9\x01\n" +
	"\x11GetStatusResponse\x12\x1c\n" +
	"\tconnected\x18\x01 \x01(\bR\tconnected\x12\x19\n" +
	"\bsteam_id\x18\x02 \x01(\tR\asteamId\x12#\n" +
	"\rcurrent_appid\x18\x03 \x01(\rR\fcurrentAppid\x12\x16\n" +
	"\x06uptime\x18\x04 \x01(\tR\x06uptime\x12!\n" +
	"\fmemory_bytes\x18\x05 \x01(\x04R\vmemoryBytes\x12(\n" +
	"\x10current_app_name\x18\x06 \x01(\tR\x0ecurrentAppName\x12!\n" +
	"\fpersona_name\x18\a \x01(\tR\vpersonaName\"\x13\n" +
	"\x11StopDaemonRequest\".\n" +
	"\x12StopDaemonResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"'\n" +
	"\x0fPlayGameRequest\x12\x14\n" +
	"\x05appid\x18\x01 \x01(\rR\x05appid\",\n" +
	"\x10PlayGameResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\x11\n" +
	"\x0fExitGameRequest\",\n" +
	"\x10ExitGameResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\xd6\x02\n" +
	"\x04Item\x12\x19\n" +
	"\basset_id\x18\x01 \x01(\x04R\aassetId\x12\x1b\n" +
	"\tdef_index\x18\x02 \x01(\rR\bdefIndex\x12\x18\n" +
	"\aquality\x18\x03 \x01(\rR\aquality\x12\x1a\n" +
	"\bquantity\x18\x04 \x01(\rR\bquantity\x12\x1f\n" +
	"\vis_tradable\x18\x05 \x01(\bR\n" +
	"isTradable\x12!\n" +
	"\fis_craftable\x18\x06 \x01(\bR\visCraftable\x12<\n" +
	"\n" +
	"attributes\x18\a \x03(\v2\x1c.daemon.Item.AttributesEntryR\n" +
	"attributes\x12\x1f\n" +
	"\voriginal_id\x18\b \x01(\x04R\n" +
	"originalId\x1a=\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xbb\x01\n" +
	"\x11ExecActionRequest\x12\x14\n" +
	"\x05appid\x18\x01 \x01(\rR\x05appid\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action\x12=\n" +
	"\x06params\x18\x03 \x03(\v2%.daemon.ExecActionRequest.ParamsEntryR\x06params\x1a9\n" +
	"\vParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"l\n" +
	"\x12ExecActionResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\"\n" +
	"\x05items\x18\x02 \x03(\v2\f.daemon.ItemR\x05items\x12\x18\n" +
	"\adetails\x18\x03 \x01(\tR\adetails\"\x15\n" +
	"\x13StreamEventsRequest\"\x91\x01\n" +
	"\x14StreamEventsResponse\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x1d\n" +
	"\n" +
	"event_type\x18\x02 \x01(\tR\teventType\x12!\n" +
	"\fpayload_json\x18\x03 \x01(\tR\vpayloadJson\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\"\x86\x01\n" +
	"\x10ManualPriceEntry\x12\x19\n" +
	"\bbuy_keys\x18\x01 \x01(\rR\abuyKeys\x12\x1b\n" +
	"\tbuy_metal\x18\x02 \x01(\x01R\bbuyMetal\x12\x1b\n" +
	"\tsell_keys\x18\x03 \x01(\rR\bsellKeys\x12\x1d\n" +
	"\n" +
	"sell_metal\x18\x04 \x01(\x01R\tsellMetal\"\xb7\x01\n" +
	"\x19UpdateManualPricesRequest\x12E\n" +
	"\x06prices\x18\x01 \x03(\v2-.daemon.UpdateManualPricesRequest.PricesEntryR\x06prices\x1aS\n" +
	"\vPricesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12.\n" +
	"\x05value\x18\x02 \x01(\v2\x18.daemon.ManualPriceEntryR\x05value:\x028\x01\"P\n" +
	"\x1aUpdateManualPricesResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\"\x12\n" +
	"\x10GuardCodeRequest\"'\n" +
	"\x11GuardCodeResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\"\x8e\x01\n" +
	"\x11GuardConfirmation\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x14\n" +
	"\x05nonce\x18\x02 \x01(\x04R\x05nonce\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x1b\n" +
	"\ttype_name\x18\x04 \x01(\tR\btypeName\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\"\x12\n" +
	"\x10GuardListRequest\"T\n" +
	"\x11GuardListResponse\x12?\n" +
	"\rconfirmations\x18\x01 \x03(\v2\x19.daemon.GuardConfirmationR\rconfirmations\"h\n" +
	"\x13GuardRespondRequest\x12'\n" +
	"\x0fconfirmation_id\x18\x01 \x01(\x04R\x0econfirmationId\x12\x16\n" +
	"\x06accept\x18\x02 \x01(\bR\x06accept\x12\x10\n" +
	"\x03all\x18\x03 \x01(\bR\x03all\"J\n" +
	"\x14GuardRespondResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x14\n" +
	"\x12GuardStatusRequest\"\xdd\x01\n" +
	"\x13GuardStatusResponse\x12\x1e\n" +
	"\n" +
	"configured\x18\x01 \x01(\bR\n" +
	"configured\x12\x1b\n" +
	"\tdevice_id\x18\x02 \x01(\tR\bdeviceId\x12\x19\n" +
	"\bsteam_id\x18\x03 \x01(\tR\asteamId\x12\x14\n" +
	"\x05state\x18\x04 \x01(\rR\x05state\x12#\n" +
	"\rshared_secret\x18\x05 \x01(\tR\fsharedSecret\x12\x10\n" +
	"\x03uri\x18\x06 \x01(\tR\x03uri\x12!\n" +
	"\faccount_name\x18\a \x01(\tR\vaccountName\"\xc7\x01\n" +
	"\x12GuardImportRequest\x12#\n" +
	"\rshared_secret\x18\x01 \x01(\tR\fsharedSecret\x12'\n" +
	"\x0fidentity_secret\x18\x02 \x01(\tR\x0eidentitySecret\x12\x1b\n" +
	"\tdevice_id\x18\x03 \x01(\tR\bdeviceId\x12!\n" +
	"\faccount_name\x18\x04 \x01(\tR\vaccountName\x12#\n" +
	"\rrefresh_token\x18\x05 \x01(\tR\frefreshToken\"I\n" +
	"\x13GuardImportResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xa7\a\n" +
	"\rDaemonService\x12@\n" +
	"\tGetStatus\x12\x18.daemon.GetStatusRequest\x1a\x19.daemon.GetStatusResponse\x12C\n" +
	"\n" +
	"StopDaemon\x12\x19.daemon.StopDaemonRequest\x1a\x1a.daemon.StopDaemonResponse\x12=\n" +
	"\bPlayGame\x12\x17.daemon.PlayGameRequest\x1a\x18.daemon.PlayGameResponse\x12=\n" +
	"\bExitGame\x12\x17.daemon.ExitGameRequest\x1a\x18.daemon.ExitGameResponse\x12C\n" +
	"\n" +
	"ExecAction\x12\x19.daemon.ExecActionRequest\x1a\x1a.daemon.ExecActionResponse\x12C\n" +
	"\n" +
	"FreeMemory\x12\x19.daemon.FreeMemoryRequest\x1a\x1a.daemon.FreeMemoryResponse\x12K\n" +
	"\fStreamEvents\x12\x1b.daemon.StreamEventsRequest\x1a\x1c.daemon.StreamEventsResponse0\x01\x12[\n" +
	"\x12UpdateManualPrices\x12!.daemon.UpdateManualPricesRequest\x1a\".daemon.UpdateManualPricesResponse\x12@\n" +
	"\tGuardCode\x12\x18.daemon.GuardCodeRequest\x1a\x19.daemon.GuardCodeResponse\x12F\n" +
	"\vGuardStatus\x12\x1a.daemon.GuardStatusRequest\x1a\x1b.daemon.GuardStatusResponse\x12@\n" +
	"\tGuardList\x12\x18.daemon.GuardListRequest\x1a\x19.daemon.GuardListResponse\x12I\n" +
	"\fGuardRespond\x12\x1b.daemon.GuardRespondRequest\x1a\x1c.daemon.GuardRespondResponse\x12F\n" +
	"\vGuardImport\x12\x1a.daemon.GuardImportRequest\x1a\x1b.daemon.GuardImportResponseB.Z,github.com/lemon4ksan/g-man-cli/proto/daemonb\x06proto3"

var (
	file_daemon_proto_rawDescOnce sync.Once
	file_daemon_proto_rawDescData []byte
)

func file_daemon_proto_rawDescGZIP() []byte {
	file_daemon_proto_rawDescOnce.Do(func() {
		file_daemon_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_daemon_proto_rawDesc), len(file_daemon_proto_rawDesc)))
	})
	return file_daemon_proto_rawDescData
}

var file_daemon_proto_msgTypes = make([]protoimpl.MessageInfo, 32)
var file_daemon_proto_goTypes = []any{
	(*FreeMemoryRequest)(nil),          // 0: daemon.FreeMemoryRequest
	(*FreeMemoryResponse)(nil),         // 1: daemon.FreeMemoryResponse
	(*GetStatusRequest)(nil),           // 2: daemon.GetStatusRequest
	(*GetStatusResponse)(nil),          // 3: daemon.GetStatusResponse
	(*StopDaemonRequest)(nil),          // 4: daemon.StopDaemonRequest
	(*StopDaemonResponse)(nil),         // 5: daemon.StopDaemonResponse
	(*PlayGameRequest)(nil),            // 6: daemon.PlayGameRequest
	(*PlayGameResponse)(nil),           // 7: daemon.PlayGameResponse
	(*ExitGameRequest)(nil),            // 8: daemon.ExitGameRequest
	(*ExitGameResponse)(nil),           // 9: daemon.ExitGameResponse
	(*Item)(nil),                       // 10: daemon.Item
	(*ExecActionRequest)(nil),          // 11: daemon.ExecActionRequest
	(*ExecActionResponse)(nil),         // 12: daemon.ExecActionResponse
	(*StreamEventsRequest)(nil),        // 13: daemon.StreamEventsRequest
	(*StreamEventsResponse)(nil),       // 14: daemon.StreamEventsResponse
	(*ManualPriceEntry)(nil),           // 15: daemon.ManualPriceEntry
	(*UpdateManualPricesRequest)(nil),  // 16: daemon.UpdateManualPricesRequest
	(*UpdateManualPricesResponse)(nil), // 17: daemon.UpdateManualPricesResponse
	(*GuardCodeRequest)(nil),           // 18: daemon.GuardCodeRequest
	(*GuardCodeResponse)(nil),          // 19: daemon.GuardCodeResponse
	(*GuardConfirmation)(nil),          // 20: daemon.GuardConfirmation
	(*GuardListRequest)(nil),           // 21: daemon.GuardListRequest
	(*GuardListResponse)(nil),          // 22: daemon.GuardListResponse
	(*GuardRespondRequest)(nil),        // 23: daemon.GuardRespondRequest
	(*GuardRespondResponse)(nil),       // 24: daemon.GuardRespondResponse
	(*GuardStatusRequest)(nil),         // 25: daemon.GuardStatusRequest
	(*GuardStatusResponse)(nil),        // 26: daemon.GuardStatusResponse
	(*GuardImportRequest)(nil),         // 27: daemon.GuardImportRequest
	(*GuardImportResponse)(nil),        // 28: daemon.GuardImportResponse
	nil,                                // 29: daemon.Item.AttributesEntry
	nil,                                // 30: daemon.ExecActionRequest.ParamsEntry
	nil,                                // 31: daemon.UpdateManualPricesRequest.PricesEntry
}
var file_daemon_proto_depIdxs = []int32{
	29, // 0: daemon.Item.attributes:type_name -> daemon.Item.AttributesEntry
	30, // 1: daemon.ExecActionRequest.params:type_name -> daemon.ExecActionRequest.ParamsEntry
	10, // 2: daemon.ExecActionResponse.items:type_name -> daemon.Item
	31, // 3: daemon.UpdateManualPricesRequest.prices:type_name -> daemon.UpdateManualPricesRequest.PricesEntry
	20, // 4: daemon.GuardListResponse.confirmations:type_name -> daemon.GuardConfirmation
	15, // 5: daemon.UpdateManualPricesRequest.PricesEntry.value:type_name -> daemon.ManualPriceEntry
	2,  // 6: daemon.DaemonService.GetStatus:input_type -> daemon.GetStatusRequest
	4,  // 7: daemon.DaemonService.StopDaemon:input_type -> daemon.StopDaemonRequest
	6,  // 8: daemon.DaemonService.PlayGame:input_type -> daemon.PlayGameRequest
	8,  // 9: daemon.DaemonService.ExitGame:input_type -> daemon.ExitGameRequest
	11, // 10: daemon.DaemonService.ExecAction:input_type -> daemon.ExecActionRequest
	0,  // 11: daemon.DaemonService.FreeMemory:input_type -> daemon.FreeMemoryRequest
	13, // 12: daemon.DaemonService.StreamEvents:input_type -> daemon.StreamEventsRequest
	16, // 13: daemon.DaemonService.UpdateManualPrices:input_type -> daemon.UpdateManualPricesRequest
	18, // 14: daemon.DaemonService.GuardCode:input_type -> daemon.GuardCodeRequest
	25, // 15: daemon.DaemonService.GuardStatus:input_type -> daemon.GuardStatusRequest
	21, // 16: daemon.DaemonService.GuardList:input_type -> daemon.GuardListRequest
	23, // 17: daemon.DaemonService.GuardRespond:input_type -> daemon.GuardRespondRequest
	27, // 18: daemon.DaemonService.GuardImport:input_type -> daemon.GuardImportRequest
	3,  // 19: daemon.DaemonService.GetStatus:output_type -> daemon.GetStatusResponse
	5,  // 20: daemon.DaemonService.StopDaemon:output_type -> daemon.StopDaemonResponse
	7,  // 21: daemon.DaemonService.PlayGame:output_type -> daemon.PlayGameResponse
	9,  // 22: daemon.DaemonService.ExitGame:output_type -> daemon.ExitGameResponse
	12, // 23: daemon.DaemonService.ExecAction:output_type -> daemon.ExecActionResponse
	1,  // 24: daemon.DaemonService.FreeMemory:output_type -> daemon.FreeMemoryResponse
	14, // 25: daemon.DaemonService.StreamEvents:output_type -> daemon.StreamEventsResponse
	17, // 26: daemon.DaemonService.UpdateManualPrices:output_type -> daemon.UpdateManualPricesResponse
	19, // 27: daemon.DaemonService.GuardCode:output_type -> daemon.GuardCodeResponse
	26, // 28: daemon.DaemonService.GuardStatus:output_type -> daemon.GuardStatusResponse
	22, // 29: daemon.DaemonService.GuardList:output_type -> daemon.GuardListResponse
	24, // 30: daemon.DaemonService.GuardRespond:output_type -> daemon.GuardRespondResponse
	28, // 31: daemon.DaemonService.GuardImport:output_type -> daemon.GuardImportResponse
	19, // [19:32] is the sub-list for method output_type
	6,  // [6:19] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_daemon_proto_init() }
func file_daemon_proto_init() {
	if File_daemon_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_daemon_proto_rawDesc), len(file_daemon_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   32,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_daemon_proto_goTypes,
		DependencyIndexes: file_daemon_proto_depIdxs,
		MessageInfos:      file_daemon_proto_msgTypes,
	}.Build()
	File_daemon_proto = out.File
	file_daemon_proto_goTypes = nil
	file_daemon_proto_depIdxs = nil
}
