// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v6.33.5
// source: daemon.proto

package daemon

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DaemonService_GetStatus_FullMethodName          = "/daemon.DaemonService/GetStatus"
	DaemonService_StopDaemon_FullMethodName         = "/daemon.DaemonService/StopDaemon"
	DaemonService_PlayGame_FullMethodName           = "/daemon.DaemonService/PlayGame"
	DaemonService_ExitGame_FullMethodName           = "/daemon.DaemonService/ExitGame"
	DaemonService_ExecAction_FullMethodName         = "/daemon.DaemonService/ExecAction"
	DaemonService_FreeMemory_FullMethodName         = "/daemon.DaemonService/FreeMemory"
	DaemonService_StreamEvents_FullMethodName       = "/daemon.DaemonService/StreamEvents"
	DaemonService_UpdateManualPrices_FullMethodName = "/daemon.DaemonService/UpdateManualPrices"
	DaemonService_GuardCode_FullMethodName          = "/daemon.DaemonService/GuardCode"
	DaemonService_GuardStatus_FullMethodName        = "/daemon.DaemonService/GuardStatus"
	DaemonService_GuardList_FullMethodName          = "/daemon.DaemonService/GuardList"
	DaemonService_GuardRespond_FullMethodName       = "/daemon.DaemonService/GuardRespond"
	DaemonService_GuardImport_FullMethodName        = "/daemon.DaemonService/GuardImport"
)

// DaemonServiceClient is the client API for DaemonService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DaemonServiceClient interface {
	GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*GetStatusResponse, error)
	StopDaemon(ctx context.Context, in *StopDaemonRequest, opts ...grpc.CallOption) (*StopDaemonResponse, error)
	PlayGame(ctx context.Context, in *PlayGameRequest, opts ...grpc.CallOption) (*PlayGameResponse, error)
	ExitGame(ctx context.Context, in *ExitGameRequest, opts ...grpc.CallOption) (*ExitGameResponse, error)
	ExecAction(ctx context.Context, in *ExecActionRequest, opts ...grpc.CallOption) (*ExecActionResponse, error)
	FreeMemory(ctx context.Context, in *FreeMemoryRequest, opts ...grpc.CallOption) (*FreeMemoryResponse, error)
	StreamEvents(ctx context.Context, in *StreamEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamEventsResponse], error)
	UpdateManualPrices(ctx context.Context, in *UpdateManualPricesRequest, opts ...grpc.CallOption) (*UpdateManualPricesResponse, error)
	GuardCode(ctx context.Context, in *GuardCodeRequest, opts ...grpc.CallOption) (*GuardCodeResponse, error)
	GuardStatus(ctx context.Context, in *GuardStatusRequest, opts ...grpc.CallOption) (*GuardStatusResponse, error)
	GuardList(ctx context.Context, in *GuardListRequest, opts ...grpc.CallOption) (*GuardListResponse, error)
	GuardRespond(ctx context.Context, in *GuardRespondRequest, opts ...grpc.CallOption) (*GuardRespondResponse, error)
	GuardImport(ctx context.Context, in *GuardImportRequest, opts ...grpc.CallOption) (*GuardImportResponse, error)
}

type daemonServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDaemonServiceClient(cc grpc.ClientConnInterface) DaemonServiceClient {
	return &daemonServiceClient{cc}
}

func (c *daemonServiceClient) GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*GetStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStatusResponse)
	err := c.cc.Invoke(ctx, DaemonService_GetStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) StopDaemon(ctx context.Context, in *StopDaemonRequest, opts ...grpc.CallOption) (*StopDaemonResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StopDaemonResponse)
	err := c.cc.Invoke(ctx, DaemonService_StopDaemon_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) PlayGame(ctx context.Context, in *PlayGameRequest, opts ...grpc.CallOption) (*PlayGameResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PlayGameResponse)
	err := c.cc.Invoke(ctx, DaemonService_PlayGame_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) ExitGame(ctx context.Context, in *ExitGameRequest, opts ...grpc.CallOption) (*ExitGameResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExitGameResponse)
	err := c.cc.Invoke(ctx, DaemonService_ExitGame_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) ExecAction(ctx context.Context, in *ExecActionRequest, opts ...grpc.CallOption) (*ExecActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecActionResponse)
	err := c.cc.Invoke(ctx, DaemonService_ExecAction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) FreeMemory(ctx context.Context, in *FreeMemoryRequest, opts ...grpc.CallOption) (*FreeMemoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FreeMemoryResponse)
	err := c.cc.Invoke(ctx, DaemonService_FreeMemory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) StreamEvents(ctx context.Context, in *StreamEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamEventsResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DaemonService_ServiceDesc.Streams[0], DaemonService_StreamEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamEventsRequest, StreamEventsResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DaemonService_StreamEventsClient = grpc.ServerStreamingClient[StreamEventsResponse]

func (c *daemonServiceClient) UpdateManualPrices(ctx context.Context, in *UpdateManualPricesRequest, opts ...grpc.CallOption) (*UpdateManualPricesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateManualPricesResponse)
	err := c.cc.Invoke(ctx, DaemonService_UpdateManualPrices_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) GuardCode(ctx context.Context, in *GuardCodeRequest, opts ...grpc.CallOption) (*GuardCodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GuardCodeResponse)
	err := c.cc.Invoke(ctx, DaemonService_GuardCode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) GuardStatus(ctx context.Context, in *GuardStatusRequest, opts ...grpc.CallOption) (*GuardStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GuardStatusResponse)
	err := c.cc.Invoke(ctx, DaemonService_GuardStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) GuardList(ctx context.Context, in *GuardListRequest, opts ...grpc.CallOption) (*GuardListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GuardListResponse)
	err := c.cc.Invoke(ctx, DaemonService_GuardList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) GuardRespond(ctx context.Context, in *GuardRespondRequest, opts ...grpc.CallOption) (*GuardRespondResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GuardRespondResponse)
	err := c.cc.Invoke(ctx, DaemonService_GuardRespond_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) GuardImport(ctx context.Context, in *GuardImportRequest, opts ...grpc.CallOption) (*GuardImportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GuardImportResponse)
	err := c.cc.Invoke(ctx, DaemonService_GuardImport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DaemonServiceServer is the server API for DaemonService service.
// All implementations must embed UnimplementedDaemonServiceServer
// for forward compatibility.
type DaemonServiceServer interface {
	GetStatus(context.Context, *GetStatusRequest) (*GetStatusResponse, error)
	StopDaemon(context.Context, *StopDaemonRequest) (*StopDaemonResponse, error)
	PlayGame(context.Context, *PlayGameRequest) (*PlayGameResponse, error)
	ExitGame(context.Context, *ExitGameRequest) (*ExitGameResponse, error)
	ExecAction(context.Context, *ExecActionRequest) (*ExecActionResponse, error)
	FreeMemory(context.Context, *FreeMemoryRequest) (*FreeMemoryResponse, error)
	StreamEvents(*StreamEventsRequest, grpc.ServerStreamingServer[StreamEventsResponse]) error
	UpdateManualPrices(context.Context, *UpdateManualPricesRequest) (*UpdateManualPricesResponse, error)
	GuardCode(context.Context, *GuardCodeRequest) (*GuardCodeResponse, error)
	GuardStatus(context.Context, *GuardStatusRequest) (*GuardStatusResponse, error)
	GuardList(context.Context, *GuardListRequest) (*GuardListResponse, error)
	GuardRespond(context.Context, *GuardRespondRequest) (*GuardRespondResponse, error)
	GuardImport(context.Context, *GuardImportRequest) (*GuardImportResponse, error)
	mustEmbedUnimplementedDaemonServiceServer()
}

// UnimplementedDaemonServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDaemonServiceServer struct{}

func (UnimplementedDaemonServiceServer) GetStatus(context.Context, *GetStatusRequest) (*GetStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStatus not implemented")
}
func (UnimplementedDaemonServiceServer) StopDaemon(context.Context, *StopDaemonRequest) (*StopDaemonResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StopDaemon not implemented")
}
func (UnimplementedDaemonServiceServer) PlayGame(context.Context, *PlayGameRequest) (*PlayGameResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PlayGame not implemented")
}
func (UnimplementedDaemonServiceServer) ExitGame(context.Context, *ExitGameRequest) (*ExitGameResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExitGame not implemented")
}
func (UnimplementedDaemonServiceServer) ExecAction(context.Context, *ExecActionRequest) (*ExecActionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExecAction not implemented")
}
func (UnimplementedDaemonServiceServer) FreeMemory(context.Context, *FreeMemoryRequest) (*FreeMemoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FreeMemory not implemented")
}
func (UnimplementedDaemonServiceServer) StreamEvents(*StreamEventsRequest, grpc.ServerStreamingServer[StreamEventsResponse]) error {
	return status.Error(codes.Unimplemented, "method StreamEvents not implemented")
}
func (UnimplementedDaemonServiceServer) UpdateManualPrices(context.Context, *UpdateManualPricesRequest) (*UpdateManualPricesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateManualPrices not implemented")
}
func (UnimplementedDaemonServiceServer) GuardCode(context.Context, *GuardCodeRequest) (*GuardCodeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GuardCode not implemented")
}
func (UnimplementedDaemonServiceServer) GuardStatus(context.Context, *GuardStatusRequest) (*GuardStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GuardStatus not implemented")
}
func (UnimplementedDaemonServiceServer) GuardList(context.Context, *GuardListRequest) (*GuardListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GuardList not implemented")
}
func (UnimplementedDaemonServiceServer) GuardRespond(context.Context, *GuardRespondRequest) (*GuardRespondResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GuardRespond not implemented")
}
func (UnimplementedDaemonServiceServer) GuardImport(context.Context, *GuardImportRequest) (*GuardImportResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GuardImport not implemented")
}
func (UnimplementedDaemonServiceServer) mustEmbedUnimplementedDaemonServiceServer() {}
func (UnimplementedDaemonServiceServer) testEmbeddedByValue()                       {}

// UnsafeDaemonServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DaemonServiceServer will
// result in compilation errors.
type UnsafeDaemonServiceServer interface {
	mustEmbedUnimplementedDaemonServiceServer()
}

func RegisterDaemonServiceServer(s grpc.ServiceRegistrar, srv DaemonServiceServer) {
	// If the following call panics, it indicates UnimplementedDaemonServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DaemonService_ServiceDesc, srv)
}

func _DaemonService_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_GetStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).GetStatus(ctx, req.(*GetStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_StopDaemon_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopDaemonRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).StopDaemon(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_StopDaemon_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).StopDaemon(ctx, req.(*StopDaemonRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_PlayGame_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlayGameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).PlayGame(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_PlayGame_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).PlayGame(ctx, req.(*PlayGameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_ExitGame_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExitGameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).ExitGame(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_ExitGame_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).ExitGame(ctx, req.(*ExitGameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_ExecAction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).ExecAction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_ExecAction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).ExecAction(ctx, req.(*ExecActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_FreeMemory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FreeMemoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).FreeMemory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_FreeMemory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).FreeMemory(ctx, req.(*FreeMemoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_StreamEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamEventsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DaemonServiceServer).StreamEvents(m, &grpc.GenericServerStream[StreamEventsRequest, StreamEventsResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DaemonService_StreamEventsServer = grpc.ServerStreamingServer[StreamEventsResponse]

func _DaemonService_UpdateManualPrices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateManualPricesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).UpdateManualPrices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_UpdateManualPrices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).UpdateManualPrices(ctx, req.(*UpdateManualPricesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_GuardCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GuardCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).GuardCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_GuardCode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).GuardCode(ctx, req.(*GuardCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_GuardStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GuardStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).GuardStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_GuardStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).GuardStatus(ctx, req.(*GuardStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_GuardList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GuardListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).GuardList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_GuardList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).GuardList(ctx, req.(*GuardListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_GuardRespond_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GuardRespondRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).GuardRespond(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_GuardRespond_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).GuardRespond(ctx, req.(*GuardRespondRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_GuardImport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GuardImportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).GuardImport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_GuardImport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).GuardImport(ctx, req.(*GuardImportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DaemonService_ServiceDesc is the grpc.ServiceDesc for DaemonService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DaemonService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "daemon.DaemonService",
	HandlerType: (*DaemonServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetStatus",
			Handler:    _DaemonService_GetStatus_Handler,
		},
		{
			MethodName: "StopDaemon",
			Handler:    _DaemonService_StopDaemon_Handler,
		},
		{
			MethodName: "PlayGame",
			Handler:    _DaemonService_PlayGame_Handler,
		},
		{
			MethodName: "ExitGame",
			Handler:    _DaemonService_ExitGame_Handler,
		},
		{
			MethodName: "ExecAction",
			Handler:    _DaemonService_ExecAction_Handler,
		},
		{
			MethodName: "FreeMemory",
			Handler:    _DaemonService_FreeMemory_Handler,
		},
		{
			MethodName: "UpdateManualPrices",
			Handler:    _DaemonService_UpdateManualPrices_Handler,
		},
		{
			MethodName: "GuardCode",
			Handler:    _DaemonService_GuardCode_Handler,
		},
		{
			MethodName: "GuardStatus",
			Handler:    _DaemonService_GuardStatus_Handler,
		},
		{
			MethodName: "GuardList",
			Handler:    _DaemonService_GuardList_Handler,
		},
		{
			MethodName: "GuardRespond",
			Handler:    _DaemonService_GuardRespond_Handler,
		},
		{
			MethodName: "GuardImport",
			Handler:    _DaemonService_GuardImport_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamEvents",
			Handler:       _DaemonService_StreamEvents_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "daemon.proto",
}
