// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: pkg/protobuf/daemon/daemon.proto

package daemon

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusRequest) Reset() {
	*x = GetStatusRequest{}
	mi := &file_pkg_protobuf_daemon_daemon_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusRequest) ProtoMessage() {}

func (x *GetStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protobuf_daemon_daemon_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusRequest.ProtoReflect.Descriptor instead.
func (*GetStatusRequest) Descriptor() ([]byte, []int) {
	return file_pkg_protobuf_daemon_daemon_proto_rawDescGZIP(), []int{0}
}

type GetStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Connected     bool                   `protobuf:"varint,1,opt,name=connected,proto3" json:"connected,omitempty"`
	SteamId       string                 `protobuf:"bytes,2,opt,name=steam_id,json=steamId,proto3" json:"steam_id,omitempty"`
	CurrentAppid  uint32                 `protobuf:"varint,3,opt,name=current_appid,json=currentAppid,proto3" json:"current_appid,omitempty"`
	Uptime        string                 `protobuf:"bytes,4,opt,name=uptime,proto3" json:"uptime,omitempty"`
	MemoryBytes   uint64                 `protobuf:"varint,5,opt,name=memory_bytes,json=memoryBytes,proto3" json:"memory_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusResponse) Reset() {
	*x = GetStatusResponse{}
	mi := &file_pkg_protobuf_daemon_daemon_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusResponse) ProtoMessage() {}

func (x *GetStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protobuf_daemon_daemon_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusResponse.ProtoReflect.Descriptor instead.
func (*GetStatusResponse) Descriptor() ([]byte, []int) {
	return file_pkg_protobuf_daemon_daemon_proto_rawDescGZIP(), []int{1}
}

func (x *GetStatusResponse) GetConnected() bool {
	if x != nil {
		return x.Connected
	}
	return false
}

func (x *GetStatusResponse) GetSteamId() string {
	if x != nil {
		return x.SteamId
	}
	return ""
}

func (x *GetStatusResponse) GetCurrentAppid() uint32 {
	if x != nil {
		return x.CurrentAppid
	}
	return 0
}

func (x *GetStatusResponse) GetUptime() string {
	if x != nil {
		return x.Uptime
	}
	return ""
}

func (x *GetStatusResponse) GetMemoryBytes() uint64 {
	if x != nil {
		return x.MemoryBytes
	}
	return 0
}

type StopDaemonRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopDaemonRequest) Reset() {
	*x = StopDaemonRequest{}
	mi := &file_pkg_protobuf_daemon_daemon_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopDaemonRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopDaemonRequest) ProtoMessage() {}

func (x *StopDaemonRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protobuf_daemon_daemon_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopDaemonRequest.ProtoReflect.Descriptor instead.
func (*StopDaemonRequest) Descriptor() ([]byte, []int) {
	return file_pkg_protobuf_daemon_daemon_proto_rawDescGZIP(), []int{2}
}

type StopDaemonResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopDaemonResponse) Reset() {
	*x = StopDaemonResponse{}
	mi := &file_pkg_protobuf_daemon_daemon_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopDaemonResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopDaemonResponse) ProtoMessage() {}

func (x *StopDaemonResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protobuf_daemon_daemon_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopDaemonResponse.ProtoReflect.Descriptor instead.
func (*StopDaemonResponse) Descriptor() ([]byte, []int) {
	return file_pkg_protobuf_daemon_daemon_proto_rawDescGZIP(), []int{3}
}

func (x *StopDaemonResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type PlayGameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Appid         uint32                 `protobuf:"varint,1,opt,name=appid,proto3" json:"appid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayGameRequest) Reset() {
	*x = PlayGameRequest{}
	mi := &file_pkg_protobuf_daemon_daemon_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayGameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayGameRequest) ProtoMessage() {}

func (x *PlayGameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protobuf_daemon_daemon_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayGameRequest.ProtoReflect.Descriptor instead.
func (*PlayGameRequest) Descriptor() ([]byte, []int) {
	return file_pkg_protobuf_daemon_daemon_proto_rawDescGZIP(), []int{4}
}

func (x *PlayGameRequest) GetAppid() uint32 {
	if x != nil {
		return x.Appid
	}
	return 0
}

type PlayGameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayGameResponse) Reset() {
	*x = PlayGameResponse{}
	mi := &file_pkg_protobuf_daemon_daemon_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayGameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayGameResponse) ProtoMessage() {}

func (x *PlayGameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protobuf_daemon_daemon_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayGameResponse.ProtoReflect.Descriptor instead.
func (*PlayGameResponse) Descriptor() ([]byte, []int) {
	return file_pkg_protobuf_daemon_daemon_proto_rawDescGZIP(), []int{5}
}

func (x *PlayGameResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ExitGameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExitGameRequest) Reset() {
	*x = ExitGameRequest{}
	mi := &file_pkg_protobuf_daemon_daemon_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExitGameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExitGameRequest) ProtoMessage() {}

func (x *ExitGameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protobuf_daemon_daemon_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExitGameRequest.ProtoReflect.Descriptor instead.
func (*ExitGameRequest) Descriptor() ([]byte, []int) {
	return file_pkg_protobuf_daemon_daemon_proto_rawDescGZIP(), []int{6}
}

type ExitGameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExitGameResponse) Reset() {
	*x = ExitGameResponse{}
	mi := &file_pkg_protobuf_daemon_daemon_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExitGameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExitGameResponse) ProtoMessage() {}

func (x *ExitGameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protobuf_daemon_daemon_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExitGameResponse.ProtoReflect.Descriptor instead.
func (*ExitGameResponse) Descriptor() ([]byte, []int) {
	return file_pkg_protobuf_daemon_daemon_proto_rawDescGZIP(), []int{7}
}

func (x *ExitGameResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Item struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AssetId       uint64                 `protobuf:"varint,1,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	DefIndex      uint32                 `protobuf:"varint,2,opt,name=def_index,json=defIndex,proto3" json:"def_index,omitempty"`
	Quality       uint32                 `protobuf:"varint,3,opt,name=quality,proto3" json:"quality,omitempty"`
	Quantity      uint32                 `protobuf:"varint,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	IsTradable    bool                   `protobuf:"varint,5,opt,name=is_tradable,json=isTradable,proto3" json:"is_tradable,omitempty"`
	IsCraftable   bool                   `protobuf:"varint,6,opt,name=is_craftable,json=isCraftable,proto3" json:"is_craftable,omitempty"`
	Attributes    map[string]string      `protobuf:"bytes,7,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Item) Reset() {
	*x = Item{}
	mi := &file_pkg_protobuf_daemon_daemon_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protobuf_daemon_daemon_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item.ProtoReflect.Descriptor instead.
func (*Item) Descriptor() ([]byte, []int) {
	return file_pkg_protobuf_daemon_daemon_proto_rawDescGZIP(), []int{8}
}

func (x *Item) GetAssetId() uint64 {
	if x != nil {
		return x.AssetId
	}
	return 0
}

func (x *Item) GetDefIndex() uint32 {
	if x != nil {
		return x.DefIndex
	}
	return 0
}

func (x *Item) GetQuality() uint32 {
	if x != nil {
		return x.Quality
	}
	return 0
}

func (x *Item) GetQuantity() uint32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *Item) GetIsTradable() bool {
	if x != nil {
		return x.IsTradable
	}
	return false
}

func (x *Item) GetIsCraftable() bool {
	if x != nil {
		return x.IsCraftable
	}
	return false
}

func (x *Item) GetAttributes() map[string]string {
	if x != nil {
		return x.Attributes
	}
	return nil
}

type ExecActionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Appid         uint32                 `protobuf:"varint,1,opt,name=appid,proto3" json:"appid,omitempty"`
	Action        string                 `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	Params        map[string]string      `protobuf:"bytes,3,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecActionRequest) Reset() {
	*x = ExecActionRequest{}
	mi := &file_pkg_protobuf_daemon_daemon_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecActionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecActionRequest) ProtoMessage() {}

func (x *ExecActionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protobuf_daemon_daemon_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecActionRequest.ProtoReflect.Descriptor instead.
func (*ExecActionRequest) Descriptor() ([]byte, []int) {
	return file_pkg_protobuf_daemon_daemon_proto_rawDescGZIP(), []int{9}
}

func (x *ExecActionRequest) GetAppid() uint32 {
	if x != nil {
		return x.Appid
	}
	return 0
}

func (x *ExecActionRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *ExecActionRequest) GetParams() map[string]string {
	if x != nil {
		return x.Params
	}
	return nil
}

type ExecActionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Items         []*Item                `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecActionResponse) Reset() {
	*x = ExecActionResponse{}
	mi := &file_pkg_protobuf_daemon_daemon_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecActionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecActionResponse) ProtoMessage() {}

func (x *ExecActionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protobuf_daemon_daemon_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecActionResponse.ProtoReflect.Descriptor instead.
func (*ExecActionResponse) Descriptor() ([]byte, []int) {
	return file_pkg_protobuf_daemon_daemon_proto_rawDescGZIP(), []int{10}
}

func (x *ExecActionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ExecActionResponse) GetItems() []*Item {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_pkg_protobuf_daemon_daemon_proto protoreflect.FileDescriptor

const file_pkg_protobuf_daemon_daemon_proto_rawDesc = "" +
	"\n" +
	" pkg/protobuf/daemon/daemon.proto\x12\x06daemon\"\x12\n" +
	"\x10GetStatusRequest\"\xac\x01\n" +
	"\x11GetStatusResponse\x12\x1c\n" +
	"\tconnected\x18\x01 \x01(\bR\tconnected\x12\x19\n" +
	"\bsteam_id\x18\x02 \x01(\tR\asteamId\x12#\n" +
	"\rcurrent_appid\x18\x03 \x01(\rR\fcurrentAppid\x12\x16\n" +
	"\x06uptime\x18\x04 \x01(\tR\x06uptime\x12!\n" +
	"\fmemory_bytes\x18\x05 \x01(\x04R\vmemoryBytes\"\x13\n" +
	"\x11StopDaemonRequest\".\n" +
	"\x12StopDaemonResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"'\n" +
	"\x0fPlayGameRequest\x12\x14\n" +
	"\x05appid\x18\x01 \x01(\rR\x05appid\",\n" +
	"\x10PlayGameResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\x11\n" +
	"\x0fExitGameRequest\",\n" +
	"\x10ExitGameResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\xb5\x02\n" +
	"\x04Item\x12\x19\n" +
	"\basset_id\x18\x01 \x01(\x04R\aassetId\x12\x1b\n" +
	"\tdef_index\x18\x02 \x01(\rR\bdefIndex\x12\x18\n" +
	"\aquality\x18\x03 \x01(\rR\aquality\x12\x1a\n" +
	"\bquantity\x18\x04 \x01(\rR\bquantity\x12\x1f\n" +
	"\vis_tradable\x18\x05 \x01(\bR\n" +
	"isTradable\x12!\n" +
	"\fis_craftable\x18\x06 \x01(\bR\visCraftable\x12<\n" +
	"\n" +
	"attributes\x18\a \x03(\v2\x1c.daemon.Item.AttributesEntryR\n" +
	"attributes\x1a=\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xbb\x01\n" +
	"\x11ExecActionRequest\x12\x14\n" +
	"\x05appid\x18\x01 \x01(\rR\x05appid\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action\x12=\n" +
	"\x06params\x18\x03 \x03(\v2%.daemon.ExecActionRequest.ParamsEntryR\x06params\x1a9\n" +
	"\vParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"R\n" +
	"\x12ExecActionResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\"\n" +
	"\x05items\x18\x02 \x03(\v2\f.daemon.ItemR\x05items2\xd9\x02\n" +
	"\rDaemonService\x12@\n" +
	"\tGetStatus\x12\x18.daemon.GetStatusRequest\x1a\x19.daemon.GetStatusResponse\x12C\n" +
	"\n" +
	"StopDaemon\x12\x19.daemon.StopDaemonRequest\x1a\x1a.daemon.StopDaemonResponse\x12=\n" +
	"\bPlayGame\x12\x17.daemon.PlayGameRequest\x1a\x18.daemon.PlayGameResponse\x12=\n" +
	"\bExitGame\x12\x17.daemon.ExitGameRequest\x1a\x18.daemon.ExitGameResponse\x12C\n" +
	"\n" +
	"ExecAction\x12\x19.daemon.ExecActionRequest\x1a\x1a.daemon.ExecActionResponseB1Z/github.com/lemon4ksan/g-man/pkg/protobuf/daemonb\x06proto3"

var (
	file_pkg_protobuf_daemon_daemon_proto_rawDescOnce sync.Once
	file_pkg_protobuf_daemon_daemon_proto_rawDescData []byte
)

func file_pkg_protobuf_daemon_daemon_proto_rawDescGZIP() []byte {
	file_pkg_protobuf_daemon_daemon_proto_rawDescOnce.Do(func() {
		file_pkg_protobuf_daemon_daemon_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_protobuf_daemon_daemon_proto_rawDesc), len(file_pkg_protobuf_daemon_daemon_proto_rawDesc)))
	})
	return file_pkg_protobuf_daemon_daemon_proto_rawDescData
}

var file_pkg_protobuf_daemon_daemon_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_pkg_protobuf_daemon_daemon_proto_goTypes = []any{
	(*GetStatusRequest)(nil),   // 0: daemon.GetStatusRequest
	(*GetStatusResponse)(nil),  // 1: daemon.GetStatusResponse
	(*StopDaemonRequest)(nil),  // 2: daemon.StopDaemonRequest
	(*StopDaemonResponse)(nil), // 3: daemon.StopDaemonResponse
	(*PlayGameRequest)(nil),    // 4: daemon.PlayGameRequest
	(*PlayGameResponse)(nil),   // 5: daemon.PlayGameResponse
	(*ExitGameRequest)(nil),    // 6: daemon.ExitGameRequest
	(*ExitGameResponse)(nil),   // 7: daemon.ExitGameResponse
	(*Item)(nil),               // 8: daemon.Item
	(*ExecActionRequest)(nil),  // 9: daemon.ExecActionRequest
	(*ExecActionResponse)(nil), // 10: daemon.ExecActionResponse
	nil,                        // 11: daemon.Item.AttributesEntry
	nil,                        // 12: daemon.ExecActionRequest.ParamsEntry
}
var file_pkg_protobuf_daemon_daemon_proto_depIdxs = []int32{
	11, // 0: daemon.Item.attributes:type_name -> daemon.Item.AttributesEntry
	12, // 1: daemon.ExecActionRequest.params:type_name -> daemon.ExecActionRequest.ParamsEntry
	8,  // 2: daemon.ExecActionResponse.items:type_name -> daemon.Item
	0,  // 3: daemon.DaemonService.GetStatus:input_type -> daemon.GetStatusRequest
	2,  // 4: daemon.DaemonService.StopDaemon:input_type -> daemon.StopDaemonRequest
	4,  // 5: daemon.DaemonService.PlayGame:input_type -> daemon.PlayGameRequest
	6,  // 6: daemon.DaemonService.ExitGame:input_type -> daemon.ExitGameRequest
	9,  // 7: daemon.DaemonService.ExecAction:input_type -> daemon.ExecActionRequest
	1,  // 8: daemon.DaemonService.GetStatus:output_type -> daemon.GetStatusResponse
	3,  // 9: daemon.DaemonService.StopDaemon:output_type -> daemon.StopDaemonResponse
	5,  // 10: daemon.DaemonService.PlayGame:output_type -> daemon.PlayGameResponse
	7,  // 11: daemon.DaemonService.ExitGame:output_type -> daemon.ExitGameResponse
	10, // 12: daemon.DaemonService.ExecAction:output_type -> daemon.ExecActionResponse
	8,  // [8:13] is the sub-list for method output_type
	3,  // [3:8] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_pkg_protobuf_daemon_daemon_proto_init() }
func file_pkg_protobuf_daemon_daemon_proto_init() {
	if File_pkg_protobuf_daemon_daemon_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_protobuf_daemon_daemon_proto_rawDesc), len(file_pkg_protobuf_daemon_daemon_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_protobuf_daemon_daemon_proto_goTypes,
		DependencyIndexes: file_pkg_protobuf_daemon_daemon_proto_depIdxs,
		MessageInfos:      file_pkg_protobuf_daemon_daemon_proto_msgTypes,
	}.Build()
	File_pkg_protobuf_daemon_daemon_proto = out.File
	file_pkg_protobuf_daemon_daemon_proto_goTypes = nil
	file_pkg_protobuf_daemon_daemon_proto_depIdxs = nil
}
