// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v6.33.5
// source: paymaster.proto

package paymaster

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PaymasterBotService_CreateSteamTrade_FullMethodName = "/paymaster_bot.PaymasterBotService/CreateSteamTrade"
	PaymasterBotService_CancelSteamTrade_FullMethodName = "/paymaster_bot.PaymasterBotService/CancelSteamTrade"
)

// PaymasterBotServiceClient is the client API for PaymasterBotService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PaymasterBotServiceClient interface {
	CreateSteamTrade(ctx context.Context, in *CreateSteamTradeRequest, opts ...grpc.CallOption) (*CreateSteamTradeResponse, error)
	CancelSteamTrade(ctx context.Context, in *CancelSteamTradeRequest, opts ...grpc.CallOption) (*CancelSteamTradeResponse, error)
}

type paymasterBotServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPaymasterBotServiceClient(cc grpc.ClientConnInterface) PaymasterBotServiceClient {
	return &paymasterBotServiceClient{cc}
}

func (c *paymasterBotServiceClient) CreateSteamTrade(ctx context.Context, in *CreateSteamTradeRequest, opts ...grpc.CallOption) (*CreateSteamTradeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateSteamTradeResponse)
	err := c.cc.Invoke(ctx, PaymasterBotService_CreateSteamTrade_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymasterBotServiceClient) CancelSteamTrade(ctx context.Context, in *CancelSteamTradeRequest, opts ...grpc.CallOption) (*CancelSteamTradeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelSteamTradeResponse)
	err := c.cc.Invoke(ctx, PaymasterBotService_CancelSteamTrade_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PaymasterBotServiceServer is the server API for PaymasterBotService service.
// All implementations must embed UnimplementedPaymasterBotServiceServer
// for forward compatibility.
type PaymasterBotServiceServer interface {
	CreateSteamTrade(context.Context, *CreateSteamTradeRequest) (*CreateSteamTradeResponse, error)
	CancelSteamTrade(context.Context, *CancelSteamTradeRequest) (*CancelSteamTradeResponse, error)
	mustEmbedUnimplementedPaymasterBotServiceServer()
}

// UnimplementedPaymasterBotServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPaymasterBotServiceServer struct{}

func (UnimplementedPaymasterBotServiceServer) CreateSteamTrade(context.Context, *CreateSteamTradeRequest) (*CreateSteamTradeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSteamTrade not implemented")
}
func (UnimplementedPaymasterBotServiceServer) CancelSteamTrade(context.Context, *CancelSteamTradeRequest) (*CancelSteamTradeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelSteamTrade not implemented")
}
func (UnimplementedPaymasterBotServiceServer) mustEmbedUnimplementedPaymasterBotServiceServer() {}
func (UnimplementedPaymasterBotServiceServer) testEmbeddedByValue()                             {}

// UnsafePaymasterBotServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PaymasterBotServiceServer will
// result in compilation errors.
type UnsafePaymasterBotServiceServer interface {
	mustEmbedUnimplementedPaymasterBotServiceServer()
}

func RegisterPaymasterBotServiceServer(s grpc.ServiceRegistrar, srv PaymasterBotServiceServer) {
	// If the following call panics, it indicates UnimplementedPaymasterBotServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PaymasterBotService_ServiceDesc, srv)
}

func _PaymasterBotService_CreateSteamTrade_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSteamTradeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymasterBotServiceServer).CreateSteamTrade(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymasterBotService_CreateSteamTrade_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymasterBotServiceServer).CreateSteamTrade(ctx, req.(*CreateSteamTradeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymasterBotService_CancelSteamTrade_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelSteamTradeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymasterBotServiceServer).CancelSteamTrade(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymasterBotService_CancelSteamTrade_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymasterBotServiceServer).CancelSteamTrade(ctx, req.(*CancelSteamTradeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PaymasterBotService_ServiceDesc is the grpc.ServiceDesc for PaymasterBotService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PaymasterBotService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "paymaster_bot.PaymasterBotService",
	HandlerType: (*PaymasterBotServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateSteamTrade",
			Handler:    _PaymasterBotService_CreateSteamTrade_Handler,
		},
		{
			MethodName: "CancelSteamTrade",
			Handler:    _PaymasterBotService_CancelSteamTrade_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "paymaster.proto",
}
