// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: paymaster.proto

package paymaster

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateSteamTradeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId uint64                 `protobuf:"varint,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	TradeLink     string                 `protobuf:"bytes,2,opt,name=trade_link,json=tradeLink,proto3" json:"trade_link,omitempty"`
	KeysCount     uint32                 `protobuf:"varint,3,opt,name=keys_count,json=keysCount,proto3" json:"keys_count,omitempty"`
	MetalCount    float64                `protobuf:"fixed64,4,opt,name=metal_count,json=metalCount,proto3" json:"metal_count,omitempty"`
	SecurityCode  string                 `protobuf:"bytes,5,opt,name=security_code,json=securityCode,proto3" json:"security_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSteamTradeRequest) Reset() {
	*x = CreateSteamTradeRequest{}
	mi := &file_paymaster_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSteamTradeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSteamTradeRequest) ProtoMessage() {}

func (x *CreateSteamTradeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_paymaster_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSteamTradeRequest.ProtoReflect.Descriptor instead.
func (*CreateSteamTradeRequest) Descriptor() ([]byte, []int) {
	return file_paymaster_proto_rawDescGZIP(), []int{0}
}

func (x *CreateSteamTradeRequest) GetTransactionId() uint64 {
	if x != nil {
		return x.TransactionId
	}
	return 0
}

func (x *CreateSteamTradeRequest) GetTradeLink() string {
	if x != nil {
		return x.TradeLink
	}
	return ""
}

func (x *CreateSteamTradeRequest) GetKeysCount() uint32 {
	if x != nil {
		return x.KeysCount
	}
	return 0
}

func (x *CreateSteamTradeRequest) GetMetalCount() float64 {
	if x != nil {
		return x.MetalCount
	}
	return 0
}

func (x *CreateSteamTradeRequest) GetSecurityCode() string {
	if x != nil {
		return x.SecurityCode
	}
	return ""
}

type CreateSteamTradeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	TradeOfferId  string                 `protobuf:"bytes,2,opt,name=trade_offer_id,json=tradeOfferId,proto3" json:"trade_offer_id,omitempty"`
	SteamId_64    uint64                 `protobuf:"varint,3,opt,name=steam_id_64,json=steamId64,proto3" json:"steam_id_64,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSteamTradeResponse) Reset() {
	*x = CreateSteamTradeResponse{}
	mi := &file_paymaster_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSteamTradeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSteamTradeResponse) ProtoMessage() {}

func (x *CreateSteamTradeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_paymaster_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSteamTradeResponse.ProtoReflect.Descriptor instead.
func (*CreateSteamTradeResponse) Descriptor() ([]byte, []int) {
	return file_paymaster_proto_rawDescGZIP(), []int{1}
}

func (x *CreateSteamTradeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateSteamTradeResponse) GetTradeOfferId() string {
	if x != nil {
		return x.TradeOfferId
	}
	return ""
}

func (x *CreateSteamTradeResponse) GetSteamId_64() uint64 {
	if x != nil {
		return x.SteamId_64
	}
	return 0
}

func (x *CreateSteamTradeResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type CancelSteamTradeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TradeOfferId  string                 `protobuf:"bytes,1,opt,name=trade_offer_id,json=tradeOfferId,proto3" json:"trade_offer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelSteamTradeRequest) Reset() {
	*x = CancelSteamTradeRequest{}
	mi := &file_paymaster_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelSteamTradeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelSteamTradeRequest) ProtoMessage() {}

func (x *CancelSteamTradeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_paymaster_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelSteamTradeRequest.ProtoReflect.Descriptor instead.
func (*CancelSteamTradeRequest) Descriptor() ([]byte, []int) {
	return file_paymaster_proto_rawDescGZIP(), []int{2}
}

func (x *CancelSteamTradeRequest) GetTradeOfferId() string {
	if x != nil {
		return x.TradeOfferId
	}
	return ""
}

type CancelSteamTradeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelSteamTradeResponse) Reset() {
	*x = CancelSteamTradeResponse{}
	mi := &file_paymaster_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelSteamTradeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelSteamTradeResponse) ProtoMessage() {}

func (x *CancelSteamTradeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_paymaster_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelSteamTradeResponse.ProtoReflect.Descriptor instead.
func (*CancelSteamTradeResponse) Descriptor() ([]byte, []int) {
	return file_paymaster_proto_rawDescGZIP(), []int{3}
}

func (x *CancelSteamTradeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CancelSteamTradeResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

var File_paymaster_proto protoreflect.FileDescriptor

const file_paymaster_proto_rawDesc = "" +
	"\n" +
	"\x0fpaymaster.proto\x12\rpaymaster_bot\"\xc4\x01\n" +
	"\x17CreateSteamTradeRequest\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\x04R\rtransactionId\x12\x1d\n" +
	"\n" +
	"trade_link\x18\x02 \x01(\tR\ttradeLink\x12\x1d\n" +
	"\n" +
	"keys_count\x18\x03 \x01(\rR\tkeysCount\x12\x1f\n" +
	"\vmetal_count\x18\x04 \x01(\x01R\n" +
	"metalCount\x12#\n" +
	"\rsecurity_code\x18\x05 \x01(\tR\fsecurityCode\"\x9f\x01\n" +
	"\x18CreateSteamTradeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12$\n" +
	"\x0etrade_offer_id\x18\x02 \x01(\tR\ftradeOfferId\x12\x1e\n" +
	"\vsteam_id_64\x18\x03 \x01(\x04R\tsteamId64\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\"?\n" +
	"\x17CancelSteamTradeRequest\x12$\n" +
	"\x0etrade_offer_id\x18\x01 \x01(\tR\ftradeOfferId\"Y\n" +
	"\x18CancelSteamTradeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage2\xdf\x01\n" +
	"\x13PaymasterBotService\x12c\n" +
	"\x10CreateSteamTrade\x12&.paymaster_bot.CreateSteamTradeRequest\x1a'.paymaster_bot.CreateSteamTradeResponse\x12c\n" +
	"\x10CancelSteamTrade\x12&.paymaster_bot.CancelSteamTradeRequest\x1a'.paymaster_bot.CancelSteamTradeResponseB4Z2github.com/vlhltf/g-man-cli/pkg/protobuf/paymasterb\x06proto3"

var (
	file_paymaster_proto_rawDescOnce sync.Once
	file_paymaster_proto_rawDescData []byte
)

func file_paymaster_proto_rawDescGZIP() []byte {
	file_paymaster_proto_rawDescOnce.Do(func() {
		file_paymaster_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_paymaster_proto_rawDesc), len(file_paymaster_proto_rawDesc)))
	})
	return file_paymaster_proto_rawDescData
}

var file_paymaster_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_paymaster_proto_goTypes = []any{
	(*CreateSteamTradeRequest)(nil),  // 0: paymaster_bot.CreateSteamTradeRequest
	(*CreateSteamTradeResponse)(nil), // 1: paymaster_bot.CreateSteamTradeResponse
	(*CancelSteamTradeRequest)(nil),  // 2: paymaster_bot.CancelSteamTradeRequest
	(*CancelSteamTradeResponse)(nil), // 3: paymaster_bot.CancelSteamTradeResponse
}
var file_paymaster_proto_depIdxs = []int32{
	0, // 0: paymaster_bot.PaymasterBotService.CreateSteamTrade:input_type -> paymaster_bot.CreateSteamTradeRequest
	2, // 1: paymaster_bot.PaymasterBotService.CancelSteamTrade:input_type -> paymaster_bot.CancelSteamTradeRequest
	1, // 2: paymaster_bot.PaymasterBotService.CreateSteamTrade:output_type -> paymaster_bot.CreateSteamTradeResponse
	3, // 3: paymaster_bot.PaymasterBotService.CancelSteamTrade:output_type -> paymaster_bot.CancelSteamTradeResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_paymaster_proto_init() }
func file_paymaster_proto_init() {
	if File_paymaster_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_paymaster_proto_rawDesc), len(file_paymaster_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_paymaster_proto_goTypes,
		DependencyIndexes: file_paymaster_proto_depIdxs,
		MessageInfos:      file_paymaster_proto_msgTypes,
	}.Build()
	File_paymaster_proto = out.File
	file_paymaster_proto_goTypes = nil
	file_paymaster_proto_depIdxs = nil
}
